var HotelData = [{
  "id": 1,
  "destination": "Cox's Bazar",
  "origin": "Chittagong",
  "name": "Mother's Resourtes",
  "image": "https://i.ibb.co/PQctZ2D/1.jpg",
  "bed": 4,
  "bedrooms": 2,
  "bath": 1,
  "guests": 4,
  "cancel": "Cantallation fexibility available",
  "price": 25,
  "oppertunity": "Wif air canditioning kitchen"
},
{
  "id": 2,
  "destination": "Sreemangal",
  "origin": "Dhaka",
  "name": "The Mango House",
  "image": "https://i.ibb.co/xgzz2VG/1408f3e9406956eeca0d2cd0035027f8.jpg",
  "bed": 2,
  "bedrooms": 3,
  "bath": 2,
  "guests": 4,
  "cancel": "Cantallation fexibility is not available",
  "price": 35,
  "oppertunity": "Wif air canditioning kitchen"
},
{
  "id": 3,
  "destination": "Sundarbans",
  "origin": "Khulna",
  "name": "Trust House & Resourtes",
  "image": "https://i.ibb.co/WvFCnL6/37807192.jpg",
  "bed": 4,
  "bedrooms": 2,
  "bath": 2,
  "guests": 4,
  "cancel": "Cantallation fexibility available",
  "price": 50,
  "oppertunity": "Give extra discount"
},
{
  "id": 4,
  "destination": "Cox's Bazar",
  "origin": "Chittagong",
  "name": "Light Green",
  "image": "https://i.ibb.co/vcrZ1T2/173545339.jpg",
  "bed": 5,
  "bedrooms": 3,
  "bath": 2,
  "guests": 4,
  "cancel": "Cantallation fexibility is not available",
  "price": 65,
  "oppertunity": "we always try to satisfy our customers"
},
{
  "id": 5,
  "destination": "Sreemangal",
  "origin": "Dhaka",
  "name": "AR Lauge",
  "image": "https://i.ibb.co/cYXkmGn/a732403ed28a28889a056a72b42adb37.jpg",
  "bed": 4,
  "bedrooms": 2,
  "bath": 2,
  "guests": 4,
  "cancel": "Cantallation fexibility available",
  "price": 45,
  "oppertunity": "Wif air canditioning kitchen"
},
{
  "id": 6,
  "destination": "Sundarbans",
  "origin": "Khulna",
  "name": "Safety House BD",
  "image": "https://i.ibb.co/7NGqtP5/interior-design-room-house-home-apartment-condo-270-images-wallpaper-preview.jpg",
  "bed": 4,
  "bedrooms": 2,
  "bath": 1,
  "guests": 4,
  "cancel": "Cantallation fexibility available",
  "price": 25,
  "oppertunity": "Wif air canditioning kitchen"
},
{
  "id": 7,
  "destination": "Cox's Bazar",
  "origin": "Chittagong",
  "name": "Green Line Houses",
  "image": "https://i.ibb.co/gJJkd95/Rectangle-26.png",
  "bed": 4,
  "bedrooms": 3,
  "bath": 2,
  "guests": 4,
  "cancel": "Cantallation fexibility available",
  "price": 15,
  "oppertunity": "24hours available"
},
{
  "id": 8,
  "destination": "Sreemangal",
  "origin": "Dhaka",
  "name": "Light Bright House",
  "image": "https://i.ibb.co/hYbmNNG/Rectangle-27.png",
  "bed": 4,
  "guests": 4,
  "bedrooms": 2,
  "bath": 1,
  "cancel": "Cantallation fexibility is not available",
  "price": 35,
  "oppertunity": "Discount available"
},
{
  "id": 9,
  "destination": "Sundarbans",
  "origin": "Khulna",
  "name": "Shadow elit Resourte",
  "image": "https://i.ibb.co/VD6D6jR/Rectangle-28.png",
  "bed": 4,
  "bedrooms": 2,
  "bath": 1,
  "guests": 4,
  "cancel": "Cantallation fexibility available",
  "price": 50,
  "oppertunity": "We always always bests"
}
]

export default HotelData;